package basic

import (
	"github.com/pterm/pterm"
	"github.com/urfave/cli/v2"
	"netzer/utils"
)

func ShowHelpDetailed(c *cli.Context) error {
	utils.BasicIntro()
	pterm.Info.Println("This is the detailed help page for all netzer commands")
	pterm.Info.Println("The following commands are available:")
	pterm.Info.Println("\nAnalyzer Commands -->")
	pterm.Info.Println("1. stability-analysis")
	pterm.Info.Println("-> Run the stability analyzer")
	pterm.Info.Println("-> Description: This analyzer will create a stability report for the network by pinging different servers and checking the packet losses.")
	pterm.Info.Println("-> Usage: netzer stability-analysis [options]")
	pterm.Info.Println("-> Alias: sa, Usage with alias: netzer sa [options]")
	pterm.Info.Println("-> Options: time in seconds (default: 30)")
	pterm.Info.Println("-> Example: netzer stability-analysis 60")
	pterm.Info.Println("2. full-analysis")
	pterm.Info.Println("-> Run the full stability analyzer")
	pterm.Info.Println("-> Description: This analyzer will create a complete network stability report by pinging different servers, checking the packet losses and simultaneously speed testing the network.")
	pterm.Info.Println("-> Usage: netzer full-analysis [options]")
	pterm.Info.Println("-> Alias: fa, Usage with alias: netzer fa [options]")
	pterm.Info.Println("-> Options: time in seconds (default: 60)")
	pterm.Info.Println("-> Example: netzer full-analysis 120")
	pterm.Info.Println("3. long-analysis")
	pterm.Info.Println("-> Run the long stability analyzer")
	pterm.Info.Println("-> Description: This analyzer will create a complete network stability report by pinging different servers, checking the packet losses and simultaneously speed testing the network.")
	pterm.Info.Println("-> Usage: netzer long-analysis [options]")
	pterm.Info.Println("-> Alias: la, Usage with alias: netzer la [options]")
	pterm.Info.Println("-> Options: time in minutes (default: 5)")
	pterm.Info.Println("-> Example: netzer long-analysis 10")
	pterm.Info.Println("\nPing Commands -->")
	pterm.Info.Println("1. ping-specific-ip")
	pterm.Info.Println("-> Ping a specific IP address")
	pterm.Info.Println("-> Description: This command will ping a specific IP address")
	pterm.Info.Println("-> Usage: netzer ping-specific-ip [options]")
	pterm.Info.Println("-> Alias: psi, Usage with alias: netzer psi [options]")
	pterm.Info.Println("-> Options: IP address")
	pterm.Info.Println("-> Example: netzer ping-specific-ip 8.8.8.8")
	pterm.Info.Println("2. ping-all-ip")
	pterm.Info.Println("-> Ping all IPs and hosts in IP file")
	pterm.Info.Println("-> Description: This command will ping all IPs and hosts in the IP file")
	pterm.Info.Println("-> Usage: netzer ping-all-ip [options]")
	pterm.Info.Println("-> Alias: pai, Usage with alias: netzer pai [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer ping-all-ip")
	pterm.Info.Println("\nIP Commands -->")
	pterm.Info.Println("1. add-single-ip-to-file")
	pterm.Info.Println("-> Add a single IP to the IP file")
	pterm.Info.Println("-> Description: This command will add a single IP to the IP file")
	pterm.Info.Println("-> Usage: netzer add-single-ip-to-file [options]")
	pterm.Info.Println("-> Alias: asi, Usage with alias: netzer asi [options]")
	pterm.Info.Println("-> Options: IP address")
	pterm.Info.Println("-> Example: netzer add-single-ip-to-file 8.8.8.8")
	pterm.Info.Println("2. add-multiple-ip-to-file")
	pterm.Info.Println("-> Add multiple IPs to the IP file")
	pterm.Info.Println("-> Description: This command will add multiple IPs to the IP file")
	pterm.Info.Println("-> Usage: netzer add-multiple-ip-to-file [options]")
	pterm.Info.Println("-> Alias: ami, Usage with alias: netzer ami [options]")
	pterm.Info.Println("-> Options: IP addresses")
	pterm.Info.Println("-> Example: netzer add-multiple-ip-to-file 8.8.8.8 9.9.9.9")
	pterm.Info.Println("3. remove-single-ip-from-file")
	pterm.Info.Println("-> Remove a single IP from the IP file")
	pterm.Info.Println("-> Description: This command will remove a single IP from the IP file")
	pterm.Info.Println("-> Usage: netzer remove-single-ip-from-file [options]")
	pterm.Info.Println("-> Alias: rsi, Usage with alias: netzer rsi [options]")
	pterm.Info.Println("-> Options: IP address")
	pterm.Info.Println("-> Example: netzer remove-single-ip-from-file 8.8.8.8")
	pterm.Info.Println("4. remove-multiple-ip-from-file")
	pterm.Info.Println("-> Remove multiple IPs from the IP file")
	pterm.Info.Println("-> Description: This command will remove multiple IPs from the IP file")
	pterm.Info.Println("-> Usage: netzer remove-multiple-ip-from-file [options]")
	pterm.Info.Println("-> Alias: rmi, Usage with alias: netzer rmi [options]")
	pterm.Info.Println("-> Options: IP addresses")
	pterm.Info.Println("-> Example: netzer remove-multiple-ip-from-file 8.8.8.8 9.9.9.9")
	pterm.Info.Println("5. generate-ip-file")
	pterm.Info.Println("-> Generate a file with a list of IP addresses")
	pterm.Info.Println("-> Description: This command will generate a file with a list of IP addresses")
	pterm.Info.Println("-> Usage: netzer generate-ip-file [options]")
	pterm.Info.Println("-> Alias: gif, Usage with alias: netzer gif [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer generate-ip-file")
	pterm.Info.Println("6. use-ip-file")
	pterm.Info.Println("-> Use an IP file at a specified location")
	pterm.Info.Println("-> Description: This command will use an IP file at a specified location")
	pterm.Info.Println("-> Usage: netzer use-ip-file [options]")
	pterm.Info.Println("-> Alias: uif, Usage with alias: netzer uif [options]")
	pterm.Info.Println("-> Options: IP file location")
	pterm.Info.Println("-> Example: netzer use-ip-file /path/to/ip/file")
	pterm.Info.Println("7. read-ip-file")
	pterm.Info.Println("-> Read the IP file and display the IP addresses")
	pterm.Info.Println("-> Description: This command will read the IP file and display the IP addresses")
	pterm.Info.Println("-> Usage: netzer read-ip-file [options]")
	pterm.Info.Println("-> Alias: rif, Usage with alias: netzer rif [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer read-ip-file")
	pterm.Info.Println("\nSpeed Test Commands -->")
	pterm.Info.Println("1. speed-test-local")
	pterm.Info.Println("-> Run a speed test with respect to closest servers")
	pterm.Info.Println("-> Description: This command will run a speed test with respect to closest servers")
	pterm.Info.Println("-> Usage: netzer speed-test-local [options]")
	pterm.Info.Println("-> Alias: stl, Usage with alias: netzer stl [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer speed-test-local")
	pterm.Info.Println("2. speed-test-global")
	pterm.Info.Println("-> Run a speed test with respect to global servers")
	pterm.Info.Println("-> Description: This command will run a speed test with respect to global servers")
	pterm.Info.Println("-> Usage: netzer speed-test-global [options]")
	pterm.Info.Println("-> Alias: stg, Usage with alias: netzer stg [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer speed-test-global")
	pterm.Info.Println("\nHelp Commands -->")
	pterm.Info.Println("1. help")
	pterm.Info.Println("-> Show the help menu")
	pterm.Info.Println("-> Description: This command will show the help menu")
	pterm.Info.Println("-> Usage: netzer help [options]")
	pterm.Info.Println("-> Alias: h, Usage with alias: netzer h [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer help")
	pterm.Info.Println("2. help-detailed")
	pterm.Info.Println("-> Show the detailed help menu")
	pterm.Info.Println("-> Description: This command will show the detailed help menu")
	pterm.Info.Println("-> Usage: netzer help-detailed [options]")
	pterm.Info.Println("-> Alias: hd, Usage with alias: netzer hd [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer help-detailed")
	pterm.Info.Println("\nVersion Commands -->")
	pterm.Info.Println("1. version")
	pterm.Info.Println("-> Show the version of the application")
	pterm.Info.Println("-> Description: This command will show the version of the application")
	pterm.Info.Println("-> Usage: netzer version [options]")
	pterm.Info.Println("-> Alias: v, Usage with alias: netzer v [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer version")
	pterm.Info.Println("\nSettings Commands -->")
	pterm.Info.Println("1. set-settings")
	pterm.Info.Println("-> Set the settings")
	pterm.Info.Println("-> Description: This command will set the settings")
	pterm.Info.Println("-> Usage: netzer set-settings [options]")
	pterm.Info.Println("-> Alias: ss, Usage with alias: netzer ss [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer set-settings")
	pterm.Info.Println("2. show-settings")
	pterm.Info.Println("-> Show the settings")
	pterm.Info.Println("-> Description: This command will show the settings")
	pterm.Info.Println("-> Usage: netzer show-settings [options]")
	pterm.Info.Println("-> Alias: shs, Usage with alias: netzer shs [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer show-settings")
	pterm.Info.Println("3. wipe-settings")
	pterm.Info.Println("-> Reset the settings")
	pterm.Info.Println("-> Description: This command will reset the settings")
	pterm.Info.Println("-> Usage: netzer wipe-settings [options]")
	pterm.Info.Println("-> Alias: ws, Usage with alias: netzer ws [options]")
	pterm.Info.Println("-> Options: None")
	pterm.Info.Println("-> Example: netzer wipe-settings")
	pterm.Info.Println("\nData Interpreter Commands -->")
	pterm.Info.Println("Coming soon ...")
	// ... -> Add more commands here
	return nil
}
